#include "preset/defaults/defaults_build.h"

#include "formats/gcanim.h"
#include "preset/doc/preset_commands.h"
#include "preset/doc/preset_document.h"
#include "preset/doc/preset_enum_names.h"

#include <vector>

namespace Preset::Doc {

using namespace Build;

namespace {

Document Iidx11Attract() {
    return Document{
        .id = "iidx11-attract",
        .name = "Attract logo",
        .build = "iidx11",
        .length = 2456,
        .camera = WideLens({0.0, 0.0, -0.25}),
        .lights = StandardLights(),
        .assets = {Scene3dAsset("red", "data/graph/model/red"),
                   Package2dAsset("title", "data/graph/sys/title"),
                   Package2dAsset("system", "data/graph/sys/system")},
        .markers = {Marker{.frame = 0, .label = "Boot animation, models hidden"},
                    Marker{.frame = 502, .label = "Warp in, rotating and zooming"},
                    Marker{.frame = 793, .label = "Boot animation runs on, models hidden again"},
                    Marker{.frame = 902, .label = "Attract loop, settled to the right"},
                    Marker{.frame = 1736, .label = "Standby logo, TITLE_TAIKI looping"}},
        .tracks = {
            SpriteTrack("TITLE", "TITLE",
                        {Clip{.id = "TITLE_boot_animation_models_hidden",
                              .end = 1736,
                              .command = SpriteAnimate{.asset = "title",
                                                       .animation = "TITLE",
                                                       .priority = 15,
                                                       .playback = GcAnim::Playback::HoldLast}}}),
            SpriteTrack("TITLE_TAIKI", "TITLE_TAIKI",
                        {Clip{.id = "TITLE_TAIKI_standby_logo_title_taiki_looping",
                              .start = 1736,
                              .command = SpriteAnimate{.asset = "title",
                                                       .animation = "TITLE_TAIKI",
                                                       .priority = 15}}}),
            ModelTrack(
                "core", "core",
                {Clip{.id = "core_warp_in_rotating_and_zooming",
                      .start = 502,
                      .end = 793,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .position = Widen(0.0F, 0.0F, -0.15F),
                                           .rotation = Widen(0.0F, 8.761553F, 45.0F),
                                           .spin_per_frame = Widen(0.0F, 0.017453292F, 0.0F)}},
                 Clip{.id = "core_attract_loop_settled_to_the_right",
                      .start = 902,
                      .end = 1736,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .position = Widen(0.105F, 0.0F, 0.0F),
                                           .rotation = Widen(0.0F, 1.9678687F, 45.0F),
                                           .spin_per_frame = Widen(0.0F, 0.0021816615F, 0.0F)}},
                 Clip{.id = "core_standby_logo_title_taiki_looping",
                      .start = 1736,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .position = Widen(0.105F, 0.0F, 0.0F),
                                           .rotation = Widen(0.0F, 3.7873645F, 45.0F),
                                           .spin_per_frame = Widen(0.0F, 0.0021816615F, 0.0F)}}}),
            ModelTrack(
                "shield", "shield",
                {Clip{.id = "shield_warp_in_rotating_and_zooming",
                      .start = 502,
                      .end = 793,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .position = Widen(0.0F, 0.0F, -0.15F),
                                           .rotation = Widen(0.0F, 8.761553F, 45.0F),
                                           .spin_per_frame = Widen(0.0F, 0.017453292F, 0.0F)}},
                 Clip{.id = "shield_attract_loop_settled_to_the_right",
                      .start = 902,
                      .end = 1736,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .position = Widen(0.105F, 0.0F, 0.0F),
                                           .rotation = Widen(0.0F, 1.9678687F, 45.0F),
                                           .spin_per_frame = Widen(0.0F, 0.0021816615F, 0.0F)}},
                 Clip{.id = "shield_standby_logo_title_taiki_looping",
                      .start = 1736,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .position = Widen(0.105F, 0.0F, 0.0F),
                                           .rotation = Widen(0.0F, 3.7873645F, 45.0F),
                                           .spin_per_frame = Widen(0.0F, 0.0021816615F, 0.0F)}}}),
            ModelTrack(
                "flame", "flame",
                {Clip{.id = "flame_warp_in_rotating_and_zooming",
                      .start = 502,
                      .end = 793,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .position = Widen(0.0F, 0.0F, -0.15F),
                                           .rotation = Widen(0.0F, 8.761553F, 45.0F),
                                           .spin_per_frame = Widen(0.0F, 0.017453292F, 0.0F)}},
                 Clip{.id = "flame_attract_loop_settled_to_the_right",
                      .start = 902,
                      .end = 1736,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .position = Widen(0.105F, 0.0F, 0.0F),
                                           .rotation = Widen(0.0F, 1.9678687F, 45.0F),
                                           .spin_per_frame = Widen(0.0F, 0.0021816615F, 0.0F)}},
                 Clip{.id = "flame_standby_logo_title_taiki_looping",
                      .start = 1736,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .position = Widen(0.105F, 0.0F, 0.0F),
                                           .rotation = Widen(0.0F, 3.7873645F, 45.0F),
                                           .spin_per_frame = Widen(0.0F, 0.0021816615F, 0.0F)}}}),
            ModelTrack(
                "r_side", "r_side",
                {Clip{.id = "r_side_warp_in_rotating_and_zooming",
                      .start = 502,
                      .end = 793,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .position = Widen(0.0F, 0.0F, -0.15F),
                                           .rotation = Widen(0.0F, 8.761553F, 85.0F),
                                           .spin_per_frame = Widen(0.0F, 0.017453292F, 0.0F)}},
                 Clip{.id = "r_side_attract_loop_settled_to_the_right",
                      .start = 902,
                      .end = 1736,
                      .command = ModelDraw{.asset = "red",
                                           .anim_speed = 0.75,
                                           .position = Widen(0.105F, 0.0F, 0.0F),
                                           .rotation = Widen(0.0F, 7.8714347F, -1e+01F),
                                           .spin_per_frame = Widen(0.0F, 0.008726646F, 0.0F)}},
                 Clip{.id = "r_side_standby_logo_title_taiki_looping",
                      .start = 1736,
                      .command = ModelDraw{.asset = "red",
                                           .anim_speed = 0.75,
                                           .position = Widen(0.105F, 0.0F, 0.0F),
                                           .rotation = Widen(0.0F, 15.149458F, -1e+01F),
                                           .spin_per_frame = Widen(0.0F, 0.008726646F, 0.0F)}}}),
            CameraTrack(
                "camera",
                {Clip{.id = "camera_boot_animation_models_hidden",
                      .end = 902,
                      .command = CameraSet{.aspect = AspectSpec{.automatic = false,
                                                                .value = Widen(1.3333334F)}}}}),
            CameraTrack(
                "camera_tween",
                {Clip{.id = "camera_tween_warp_in_rotating_and_zooming",
                      .start = 502,
                      .end = 793,
                      .command = CameraTween{},
                      .keys = {Key{.at = 0,
                                   .values = {KeyValue{.id = "fov_y", .value = Widen(22.546017F)}}},
                               Key{.at = 291,
                                   .values = {KeyValue{.id = "fov_y",
                                                       .value = Widen(25.110188F)}}}}}}),
            FxTrack("fx", {Clip{.id = "fx_warp_in_rotating_and_zooming",
                                .start = 502,
                                .end = 793,
                                .command = EmitterCmd{.asset = "system",
                                                      .cell = "PTC_ORAN",
                                                      .spawn = Spawn::EveryFrame,
                                                      .count = 16,
                                                      .angle_step_deg = 22.5,
                                                      .phase_rate_deg = 32.0,
                                                      .phase_amplitude_deg = 360.0,
                                                      .radius_from = 10,
                                                      .radius_to = 630,
                                                      .reach_frames = 290,
                                                      .priority = 31,
                                                      .life = 60}}})}};
}

Document Iidx11CardIn() {
    return Document{
        .id = "iidx11-card-in",
        .name = "Card in",
        .build = "iidx11",
        .length = 3600,
        .camera = WideLens({0.0, 0.0, -0.25}),
        .lights = StandardLights(),
        .assets = {Scene3dAsset("red", "data/graph/model/red"),
                   Package2dAsset("card", "data/graph/sys/card")},
        .tracks = {
            SpriteTrack("CARD_BG", "CARD_BG",
                        {Clip{.id = "CARD_BG",
                              .command = SpriteAnimate{.asset = "card",
                                                       .animation = "CARD_BG",
                                                       .priority = 31,
                                                       .playback = GcAnim::Playback::HoldLast,
                                                       .hidden_parts = {"T_REMAIN"}}}}),
            ModelTrack("gate", "gate",
                       {Clip{.id = "gate",
                             .command = ModelDraw{.asset = "red",
                                                  .blend_mode = ModelBlend::Additive,
                                                  .alpha = 0.5,
                                                  .anim_speed = 0.25,
                                                  .rotation = Widen(-0.8F, 0.0F, 0.0F)}}})}};
}

Document Iidx11Login() {
    return Document{
        .id = "iidx11-login",
        .name = "Login",
        .build = "iidx11",
        .length = 240,
        .camera = WideLens({0.0, 0.0, -0.25}),
        .lights = StandardLights(),
        .assets = {Scene3dAsset("red", "data/graph/model/red"),
                   Package2dAsset("title", "data/graph/sys/title")},
        .tracks = {
            SpriteTrack("LOGIN", "LOGIN",
                        {Clip{.id = "LOGIN",
                              .command = SpriteAnimate{.asset = "title",
                                                       .animation = "LOGIN",
                                                       .priority = 15,
                                                       .playback = GcAnim::Playback::HideAfterEnd,
                                                       .hidden_parts = {"OP_BG_U", "OP_BG_D"}}}}),
            ModelTrack("gate", "gate",
                       {Clip{.id = "gate",
                             .command = ModelDraw{.asset = "red",
                                                  .blend_mode = ModelBlend::Additive,
                                                  .alpha = Widen(0.8F),
                                                  .rotation = Widen(-0.8F, 0.0F, 0.0F)}}})}};
}

Document Iidx11NewPlayer() {
    return Document{
        .id = "iidx11-new-player",
        .name = "New player invited",
        .build = "iidx11",
        .length = 1200,
        .camera = WideLens({0.0, 0.0, -1.0}),
        .lights = StandardLights(),
        .assets = {Scene3dAsset("red", "data/graph/model/red"),
                   Package2dAsset("card", "data/graph/sys/card")},
        .tracks = {
            SpriteTrack("CARD_BG", "CARD_BG",
                        {Clip{.id = "CARD_BG",
                              .command = SpriteAnimate{.asset = "card",
                                                       .animation = "CARD_BG",
                                                       .priority = 31,
                                                       .playback = GcAnim::Playback::HoldLast,
                                                       .hidden_parts = {"T_REMAIN"}}}}),
            ModelTrack("gate", "gate",
                       {Clip{.id = "gate",
                             .command = ModelDraw{.asset = "red",
                                                  .blend_mode = ModelBlend::Additive,
                                                  .alpha = 0.5,
                                                  .anim_speed = 0.25,
                                                  .rotation = Widen(-0.8F, 0.0F, 0.0F)}}})}};
}

}

std::vector<Document> Iidx11Defaults() {
    return {Iidx11Attract(), Iidx11CardIn(), Iidx11Login(), Iidx11NewPlayer()};
}

}
