#include "preset/defaults/defaults_build.h"

#include "preset/doc/preset_commands.h"
#include "preset/doc/preset_document.h"
#include "preset/doc/preset_enum_names.h"

namespace Preset::Doc {

using namespace Build;

DocumentPart Iidx11EndingPartB() {
    return DocumentPart{
        .markers = {Marker{.frame = 2486, .label = "Fade out, close in"},
                    Marker{.frame = 2672, .label = "Cyan burst"},
                    Marker{.frame = 2765, .label = "Blue burst"},
                    Marker{.frame = 2858, .label = "Nine degree spin"},
                    Marker{.frame = 2904, .label = "Reverse twelve"},
                    Marker{.frame = 2950, .label = "Sixteen degree spin, fading up"},
                    Marker{.frame = 3034, .label = "Logo hold"},
                    Marker{.frame = 3787, .label = "Drift out"},
                    Marker{.frame = 4065, .label = "Final push in"}},
        .tracks = {
            SpriteTrack(
                "END_BG1", "END_BG1",
                {Clip{.id = "END_BG1_fade_out_close_in",
                      .start = 2486,
                      .end = 2672,
                      .command = SpriteDraw{.asset = "ending", .cell = "END_BG1", .priority = 31}},
                 Clip{.id = "END_BG1_cyan_burst",
                      .start = 2672,
                      .end = 2765,
                      .command = SpriteDraw{.asset = "ending", .cell = "END_BG1", .priority = 31},
                      .keys = {Key{.at = 0, .values = {KeyValue{.id = "scale", .value = 1.0}}},
                               Key{.at = 92,
                                   .values = {KeyValue{.id = "scale", .value = Widen(1.92F)}}}}},
                 Clip{.id = "END_BG1_blue_burst",
                      .start = 2765,
                      .end = 2858,
                      .command = SpriteDraw{.asset = "ending", .cell = "END_BG1", .priority = 31},
                      .keys = {Key{.at = 0, .values = {KeyValue{.id = "scale", .value = 1.0}}},
                               Key{.at = 92,
                                   .values = {KeyValue{.id = "scale", .value = Widen(2.84F)}}}}},
                 Clip{.id = "END_BG1_nine_degree_spin",
                      .start = 2858,
                      .end = 2904,
                      .command = SpriteDraw{.asset = "ending", .cell = "END_BG1", .priority = 31},
                      .keys = {Key{.at = 0, .values = {KeyValue{.id = "scale", .value = 1.0}}},
                               Key{.at = 45,
                                   .values = {KeyValue{.id = "scale", .value = Widen(2.35F)}}}}},
                 Clip{.id = "END_BG1_reverse_twelve",
                      .start = 2904,
                      .end = 2950,
                      .command = SpriteDraw{.asset = "ending", .cell = "END_BG1", .priority = 31},
                      .keys = {Key{.at = 0, .values = {KeyValue{.id = "scale", .value = 3.0}}},
                               Key{.at = 45,
                                   .values = {KeyValue{.id = "scale", .value = Widen(2.1F)}}}}},
                 Clip{.id = "END_BG1_sixteen_degree_spin_fading_up",
                      .start = 2950,
                      .end = 3034,
                      .command = SpriteDraw{.asset = "ending", .cell = "END_BG1", .priority = 31},
                      .keys = {Key{.at = 0, .values = {KeyValue{.id = "scale", .value = 1.0}}},
                               Key{.at = 83,
                                   .values = {KeyValue{.id = "scale", .value = Widen(5.15F)}}}}},
                 Clip{.id = "END_BG1_logo_hold",
                      .start = 3034,
                      .command =
                          SpriteDraw{.asset = "ending", .cell = "END_BG1", .priority = 31}}}),
            ModelTrack(
                "core", "core",
                {Clip{.id = "core_fade_out_close_in",
                      .start = 2486,
                      .end = 2672,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0},
                                           .spin_per_frame = Widen(0.0F, 0.017453292F, 0.0F)}},
                 Clip{.id = "core_cyan_burst",
                      .start = 2672,
                      .end = 2765,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0}}},
                 Clip{.id = "core_blue_burst",
                      .start = 2765,
                      .end = 2858,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0}}},
                 Clip{.id = "core_nine_degree_spin",
                      .start = 2858,
                      .end = 2904,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0},
                                           .spin_per_frame = Widen(0.0F, 0.15707962F, 0.0F)}},
                 Clip{.id = "core_reverse_twelve",
                      .start = 2904,
                      .end = 2950,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0},
                                           .spin_per_frame = Widen(0.0F, -0.2094395F, 0.0F)}},
                 Clip{.id = "core_sixteen_degree_spin_fading_up",
                      .start = 2950,
                      .end = 3034,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0},
                                           .spin_per_frame = Widen(0.0F, 0.27925268F, 0.0F)}},
                 Clip{.id = "core_logo_hold",
                      .start = 3034,
                      .end = 3787,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0},
                                           .spin_per_frame = Widen(0.0F, -0.052359875F, 0.0F)}},
                 Clip{.id = "core_drift_out",
                      .start = 3787,
                      .end = 4065,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0},
                                           .spin_per_frame = Widen(0.0F, -0.052359875F, 0.0F)}},
                 Clip{.id = "core_final_push_in",
                      .start = 4065,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0},
                                           .spin_per_frame = Widen(0.0F, -0.052359875F, 0.0F)}}}),
            ModelTrack(
                "core_tween", "core",
                {Clip{.id = "core_tween_fade_out_close_in",
                      .start = 2486,
                      .end = 2672,
                      .command = ModelTween{},
                      .keys = {Key{.at = 0, .values = {KeyValue{.id = "alpha", .value = 1.0}}},
                               Key{.at = 120, .values = {KeyValue{.id = "alpha", .value = 0.0}}}}},
                 Clip{.id = "core_tween_cyan_burst",
                      .start = 2672,
                      .end = 2765,
                      .command = ModelTween{},
                      .keys = {Key{.at = 0, .values = {KeyValue{.id = "alpha", .value = 1.0}}},
                               Key{.at = 60, .values = {KeyValue{.id = "alpha", .value = 0.0}}}}},
                 Clip{.id = "core_tween_blue_burst",
                      .start = 2765,
                      .end = 2858,
                      .command = ModelTween{},
                      .keys = {Key{.at = 0, .values = {KeyValue{.id = "alpha", .value = 1.0}}},
                               Key{.at = 60, .values = {KeyValue{.id = "alpha", .value = 0.0}}}}},
                 Clip{.id = "core_tween_nine_degree_spin",
                      .start = 2858,
                      .end = 2904,
                      .command = ModelTween{},
                      .keys = {Key{.at = 0, .values = {KeyValue{.id = "alpha", .value = 1.0}}},
                               Key{.at = 60, .values = {KeyValue{.id = "alpha", .value = 0.0}}}}},
                 Clip{.id = "core_tween_sixteen_degree_spin_fading_up",
                      .start = 2950,
                      .end = 3034,
                      .command = ModelTween{},
                      .keys = {Key{.at = 0, .values = {KeyValue{.id = "alpha", .value = 0.0}}},
                               Key{.at = 60, .values = {KeyValue{.id = "alpha", .value = 1.0}}}}}}),
            ModelTrack(
                "core_tween_2", "core",
                {Clip{.id = "core_tween_cyan_burst_2",
                      .start = 2672,
                      .end = 2765,
                      .command = ModelTween{},
                      .keys = {Key{.at = 0,
                                   .ease = Ease::SineDeg,
                                   .rate_deg = 1.125,
                                   .values = {KeyValue{.id = "rotation",
                                                       .value = Vec3{0.0, 0.0, 45.0}}}},
                               Key{.at = 60,
                                   .values = {KeyValue{.id = "rotation",
                                                       .value = Widen(0.0F, 6.283186F, 45.0F)}}}}},
                 Clip{
                     .id = "core_tween_blue_burst_2",
                     .start = 2765,
                     .end = 2858,
                     .command = ModelTween{},
                     .keys = {Key{.at = 0,
                                  .ease = Ease::SineDeg,
                                  .rate_deg = 1.125,
                                  .values = {KeyValue{.id = "rotation",
                                                      .value = Vec3{0.0, 0.0, 45.0}}}},
                              Key{.at = 60,
                                  .values = {KeyValue{.id = "rotation",
                                                      .value = Widen(0.0F, 12.56637F, 45.0F)}}}}}}),
            ModelTrack("core_pulse", "core",
                       {Clip{.id = "core_pulse_logo_hold",
                             .start = 3034,
                             .end = 3787,
                             .command = ModelMotionCmd{.pulse = PulseSpec{.grid = Grid::A,
                                                                          .scale_odd = 1.5,
                                                                          .scale_even = Widen(1.2F),
                                                                          .frames = 8}}}}),
            ModelTrack(
                "flame", "flame",
                {Clip{.id = "flame_fade_out_close_in",
                      .start = 2486,
                      .end = 2672,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0},
                                           .spin_per_frame = Widen(0.0F, 0.017453292F, 0.0F)}},
                 Clip{.id = "flame_cyan_burst",
                      .start = 2672,
                      .end = 2765,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0}}},
                 Clip{.id = "flame_blue_burst",
                      .start = 2765,
                      .end = 2858,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0}}},
                 Clip{.id = "flame_nine_degree_spin",
                      .start = 2858,
                      .end = 2904,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0},
                                           .spin_per_frame = Widen(0.0F, 0.15707962F, 0.0F)}},
                 Clip{.id = "flame_reverse_twelve",
                      .start = 2904,
                      .end = 2950,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0},
                                           .spin_per_frame = Widen(0.0F, -0.2094395F, 0.0F)}},
                 Clip{.id = "flame_sixteen_degree_spin_fading_up",
                      .start = 2950,
                      .end = 3034,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0},
                                           .spin_per_frame = Widen(0.0F, 0.27925268F, 0.0F)}},
                 Clip{.id = "flame_logo_hold",
                      .start = 3034,
                      .end = 3787,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0},
                                           .spin_per_frame = Widen(0.0F, -0.052359875F, 0.0F)}},
                 Clip{.id = "flame_drift_out",
                      .start = 3787,
                      .end = 4065,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0},
                                           .spin_per_frame = Widen(0.0F, -0.052359875F, 0.0F)}},
                 Clip{.id = "flame_final_push_in",
                      .start = 4065,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0},
                                           .spin_per_frame = Widen(0.0F, -0.052359875F, 0.0F)}}}),
            ModelTrack(
                "flame_tween", "flame",
                {Clip{.id = "flame_tween_fade_out_close_in",
                      .start = 2486,
                      .end = 2672,
                      .command = ModelTween{},
                      .keys = {Key{.at = 0, .values = {KeyValue{.id = "alpha", .value = 1.0}}},
                               Key{.at = 120, .values = {KeyValue{.id = "alpha", .value = 0.0}}}}},
                 Clip{.id = "flame_tween_cyan_burst",
                      .start = 2672,
                      .end = 2765,
                      .command = ModelTween{},
                      .keys = {Key{.at = 0, .values = {KeyValue{.id = "alpha", .value = 1.0}}},
                               Key{.at = 60, .values = {KeyValue{.id = "alpha", .value = 0.0}}}}},
                 Clip{.id = "flame_tween_blue_burst",
                      .start = 2765,
                      .end = 2858,
                      .command = ModelTween{},
                      .keys = {Key{.at = 0, .values = {KeyValue{.id = "alpha", .value = 1.0}}},
                               Key{.at = 60, .values = {KeyValue{.id = "alpha", .value = 0.0}}}}},
                 Clip{.id = "flame_tween_nine_degree_spin",
                      .start = 2858,
                      .end = 2904,
                      .command = ModelTween{},
                      .keys = {Key{.at = 0, .values = {KeyValue{.id = "alpha", .value = 1.0}}},
                               Key{.at = 60, .values = {KeyValue{.id = "alpha", .value = 0.0}}}}},
                 Clip{.id = "flame_tween_sixteen_degree_spin_fading_up",
                      .start = 2950,
                      .end = 3034,
                      .command = ModelTween{},
                      .keys = {Key{.at = 0, .values = {KeyValue{.id = "alpha", .value = 0.0}}},
                               Key{.at = 60, .values = {KeyValue{.id = "alpha", .value = 1.0}}}}}}),
            ModelTrack("flame_pulse", "flame",
                       {Clip{.id = "flame_pulse_logo_hold",
                             .start = 3034,
                             .end = 3787,
                             .command = ModelMotionCmd{.pulse = PulseSpec{.grid = Grid::A,
                                                                          .scale_odd = 1.5,
                                                                          .scale_even = Widen(1.2F),
                                                                          .frames = 8}}}}),
            CameraTrack("camera", {Clip{.id = "camera_fade_out_close_in",
                                        .start = 2486,
                                        .end = 3034,
                                        .command = CameraSet{.eye = Widen(0.0F, 0.0F, -0.2F)}},
                                   Clip{.id = "camera_logo_hold",
                                        .start = 3034,
                                        .end = 4065,
                                        .command = CameraSet{.eye = Widen(0.0F, 0.0F, -0.23F)}}}),
            CameraTrack(
                "camera_tween",
                {Clip{.id = "camera_tween_final_push_in",
                      .start = 4065,
                      .command = CameraTween{},
                      .keys = {Key{.at = 0,
                                   .values = {KeyValue{.id = "eye",
                                                       .value = Widen(0.0F, 0.0F, -0.23F)}}},
                               Key{.at = 300,
                                   .values = {KeyValue{.id = "eye",
                                                       .value = Widen(0.0F, 0.0F, -1.73F)}}}}}}),
            FxTrack("fx",
                    {Clip{.id = "fx_cyan_burst",
                          .start = 2672,
                          .end = 2765,
                          .command = EmitterCmd{.asset = "system",
                                                .cell = "PTC_CYAN",
                                                .count = 480,
                                                .priority = 24,
                                                .scale_percent = 200,
                                                .scatter = Scatter{.span = {1280.0, 960.0},
                                                                   .offset = {-320.0, -240.0}},
                                                .life = 45}},
                     Clip{.id = "fx_blue_burst",
                          .start = 2765,
                          .end = 2858,
                          .command = EmitterCmd{.asset = "system",
                                                .cell = "PTC_BLUE",
                                                .count = 480,
                                                .priority = 24,
                                                .scale_percent = 200,
                                                .scatter = Scatter{.span = {1280.0, 960.0},
                                                                   .offset = {-320.0, -240.0}},
                                                .life = 45}},
                     Clip{.id = "fx_nine_degree_spin",
                          .start = 2858,
                          .end = 2904,
                          .command = EmitterCmd{.asset = "system",
                                                .cell = "PTC_ORAN",
                                                .count = 480,
                                                .priority = 24,
                                                .scale_percent = 200,
                                                .scatter = Scatter{.span = {1280.0, 960.0},
                                                                   .offset = {-320.0, -240.0}},
                                                .life = 45}},
                     Clip{.id = "fx_reverse_twelve",
                          .start = 2904,
                          .end = 2950,
                          .command = EmitterCmd{.asset = "system",
                                                .cell = "PTC_ORAN",
                                                .count = 480,
                                                .priority = 24,
                                                .scale_percent = 200,
                                                .scatter = Scatter{.span = {1280.0, 960.0},
                                                                   .offset = {-320.0, -240.0}},
                                                .life = 45}},
                     Clip{.id = "fx_sixteen_degree_spin_fading_up",
                          .start = 2950,
                          .end = 3034,
                          .command = EmitterCmd{.asset = "system",
                                                .cell = "PTC_ORAN",
                                                .spawn = Spawn::EveryFrame,
                                                .count = 32,
                                                .priority = 24,
                                                .scale_percent = 200,
                                                .scatter = Scatter{.span = {1280.0, 960.0},
                                                                   .offset = {-320.0, -240.0}},
                                                .life_base = 48,
                                                .life_span = 48}},
                     Clip{.id = "fx_logo_hold",
                          .start = 3034,
                          .end = 3787,
                          .command = EmitterCmd{.asset = "system",
                                                .cell = "PTC_BLUE",
                                                .spawn = Spawn::Beat,
                                                .count = 128,
                                                .priority = 24,
                                                .scale_percent = 200,
                                                .scatter = Scatter{.span = {1280.0, 960.0},
                                                                   .offset = {-320.0, -240.0}},
                                                .beat_odd = 1,
                                                .life_base = 48,
                                                .life_span = 48}}})}};
}

}
