#include "preset/defaults/defaults_build.h"

#include "formats/gcanim.h"
#include "preset/doc/preset_commands.h"
#include "preset/doc/preset_document.h"
#include "preset/doc/preset_enum_names.h"

#include <numbers>
#include <vector>

namespace Preset::Doc {

using namespace Build;

namespace {

Document Iidx11DanSelect() {
    return Document{
        .id = "iidx11-dan-select",
        .name = "Class course select",
        .build = "iidx11",
        .length = 1200,
        .camera = WideLens(Widen(0.0F, 0.5904508F, -0.00809017F)),
        .lights = StandardLights(),
        .assets = {Scene3dAsset("red", "data/graph/model/red"),
                   Package2dAsset("dan_e", "data/graph/sys/dan_e")},
        .options = {OptionSpec{
            .id = "course",
            .label = "Selected course",
            .transition = {.frames = 12, .step = 4},
            .choices = {ChoiceSpec{.label = "CLASS 7",
                                   .values = {ChoiceValue{.id = "model[dan_bg1].position",
                                                          .value = Vec3{0.0, 0.0, 0.0}},
                                              ChoiceValue{
                                                  .id = "camera.eye",
                                                  .value = Widen(0.0F, 0.5427051F, -0.00904509F)}}},
                        ChoiceSpec{.label = "CLASS 6",
                                   .values = {ChoiceValue{.id = "model[dan_bg1].position",
                                                          .value = Vec3{0.0, 0.0, 0.0}},
                                              ChoiceValue{.id = "camera.eye",
                                                          .value = Widen(0.0F, 0.5116934F,
                                                                         -0.01809017F)}}},
                        ChoiceSpec{.label = "CLASS 5",
                                   .values = {ChoiceValue{.id = "model[dan_bg1].position",
                                                          .value = Vec3{0.0, 0.0, 0.0}},
                                              ChoiceValue{.id = "camera.eye",
                                                          .value = Widen(
                                                              0.0F, 0.48068166F, -0.03618034F)}}},
                        ChoiceSpec{.label = "CLASS 4",
                                   .values = {ChoiceValue{.id = "model[dan_bg1].position",
                                                          .value = Vec3{0.0, 0.0, 0.0}},
                                              ChoiceValue{.id = "camera.eye",
                                                          .value = Widen(
                                                              0.0F, 0.44966993F, -0.05427051F)}}},
                        ChoiceSpec{.label = "CLASS 3",
                                   .values = {ChoiceValue{.id = "model[dan_bg1].position",
                                                          .value = Vec3{0.0, 0.0, 0.0}},
                                              ChoiceValue{.id = "camera.eye",
                                                          .value = Widen(0.0F, 0.4186582F,
                                                                         -0.07236068F)}}},
                        ChoiceSpec{.label = "CLASS 2",
                                   .values = {ChoiceValue{.id = "model[dan_bg1].position",
                                                          .value = Vec3{0.0, 0.0, 0.0}},
                                              ChoiceValue{.id = "camera.eye",
                                                          .value = Widen(0.0F, 0.3876465F,
                                                                         -0.09045085F)}}},
                        ChoiceSpec{.label = "CLASS 1",
                                   .values = {ChoiceValue{.id = "model[dan_bg1].position",
                                                          .value = Vec3{0.0, 0.0, 0.0}},
                                              ChoiceValue{.id = "camera.eye",
                                                          .value = Widen(
                                                              0.0F, 0.35663477F, -0.10854102F)}}},
                        ChoiceSpec{.label = "1ST DAN",
                                   .values = {ChoiceValue{.id = "model[dan_bg1].position",
                                                          .value = Vec3{0.0, 0.0, 0.0}},
                                              ChoiceValue{.id = "camera.eye",
                                                          .value = Widen(
                                                              0.0F, 0.32562307F, -0.12663119F)}}},
                        ChoiceSpec{.label = "2ND DAN",
                                   .values = {ChoiceValue{.id = "model[dan_bg1].position",
                                                          .value = Vec3{0.0, 0.0, 0.0}},
                                              ChoiceValue{.id = "camera.eye",
                                                          .value = Widen(
                                                              0.0F, 0.29461133F, -0.14472136F)}}},
                        ChoiceSpec{.label = "3RD DAN",
                                   .values = {ChoiceValue{.id = "model[dan_bg1].position",
                                                          .value = Vec3{0.0, 0.0, 0.0}},
                                              ChoiceValue{.id = "camera.eye",
                                                          .value = Widen(0.0F, 0.2635996F,
                                                                         -0.16281153F)}}},
                        ChoiceSpec{.label = "4TH DAN",
                                   .values = {ChoiceValue{.id = "model[dan_bg1].position",
                                                          .value = Vec3{0.0, 0.0, 0.0}},
                                              ChoiceValue{.id = "camera.eye",
                                                          .value = Widen(
                                                              0.0F, 0.23258787F, -0.1809017F)}}},
                        ChoiceSpec{.label = "5TH DAN",
                                   .values = {ChoiceValue{.id = "model[dan_bg1].position",
                                                          .value = Vec3{0.0, 0.0, 0.0}},
                                              ChoiceValue{.id = "camera.eye",
                                                          .value = Widen(
                                                              0.0F, 0.20157616F, -0.19899186F)}}},
                        ChoiceSpec{.label = "6TH DAN",
                                   .values = {ChoiceValue{.id = "model[dan_bg1].position",
                                                          .value = Vec3{0.0, 0.0, 0.0}},
                                              ChoiceValue{.id = "camera.eye",
                                                          .value = Widen(
                                                              0.0F, 0.17056444F, -0.21708204F)}}},
                        ChoiceSpec{.label = "7TH DAN",
                                   .values = {ChoiceValue{.id = "model[dan_bg1].position",
                                                          .value = Vec3{0.0, 0.0, 0.0}},
                                              ChoiceValue{.id = "camera.eye",
                                                          .value = Widen(
                                                              0.0F, 0.13955274F, -0.23517221F)}}},
                        ChoiceSpec{.label = "8TH DAN",
                                   .values = {ChoiceValue{.id = "model[dan_bg1].position",
                                                          .value = Vec3{0.0, 0.0, 0.0}},
                                              ChoiceValue{.id = "camera.eye",
                                                          .value = Widen(
                                                              0.0F, 0.10854102F, -0.25326237F)}}},
                        ChoiceSpec{.label = "9TH DAN",
                                   .values = {ChoiceValue{.id = "model[dan_bg1].position",
                                                          .value = Vec3{0.0, 0.0, 0.0}},
                                              ChoiceValue{.id = "camera.eye",
                                                          .value = Widen(
                                                              0.0F, 0.10854102F, -0.17185663F)}}},
                        ChoiceSpec{
                            .label = "10TH DAN",
                            .values = {ChoiceValue{.id = "model[dan_bg1].position",
                                                   .value = Vec3{0.0, 0.0, 0.0}},
                                       ChoiceValue{.id = "camera.eye",
                                                   .value = Widen(0.0F,
                                                                  0.10854102F, -0.09045085F)}}}}}},
        .tracks = {
            SpriteTrack("BG", "BG",
                        {Clip{.id = "BG",
                              .command = SpriteAnimate{.asset = "dan_e",
                                                       .animation = "BG",
                                                       .priority = 31,
                                                       .playback = GcAnim::Playback::HoldLast}}}),
            ModelTrack("dan_bg1", "dan_bg1",
                       {Clip{.id = "dan_bg1",
                             .command = ModelDraw{.asset = "red",
                                                  .blend_mode = ModelBlend::Additive,
                                                  .anim_speed = 0.75,
                                                  .rotation = Widen(3.14F, 0.0F, 0.0F),
                                                  .spin_per_frame = Widen(0.0F, 0.03F, 0.0F)}}}),
            ModelTrack("core", "core",
                       {Clip{.id = "core",
                             .command = ModelDraw{.asset = "red",
                                                  .blend_mode = ModelBlend::Additive,
                                                  .anim_speed = 0.75,
                                                  .spin_per_frame = Widen(0.0F, 0.015F, 0.0F)}}}),
            ModelTrack(
                "flame", "flame",
                {Clip{.id = "flame",
                      .command = ModelDraw{.asset = "red",
                                           .anim_speed = 0.75,
                                           .spin_per_frame = Widen(0.0F, -0.015F, 0.0F)}}})}};
}

Document Iidx11ExpertSelect() {
    return Document{
        .id = "iidx11-expert-select",
        .name = "Expert select",
        .build = "iidx11",
        .length = 2700,
        .camera = WideLens({0.0, 0.0, -1.0}),
        .lights = StandardLights(),
        .assets = {Scene3dAsset("red", "data/graph/model/red"),
                   Package2dAsset("expert", "data/graph/sys/expert")},
        .markers = {Marker{.frame = 0, .label = "Fly in from the eye plane"},
                    Marker{.frame = 42, .label = "Settled"},
                    Marker{.frame = 400, .label = "Outro hold, snapped to centre"},
                    Marker{.frame = 550, .label = "Outro fade"}},
        .tracks = {
            SpriteTrack("EXPERT_BG", "EXPERT_BG",
                        {Clip{.id = "EXPERT_BG_fly_in_from_the_eye_plane",
                              .end = 400,
                              .command = SpriteAnimate{.asset = "expert",
                                                       .animation = "EXPERT_BG",
                                                       .priority = 31,
                                                       .playback = GcAnim::Playback::HoldLast}}}),
            SpriteTrack("COURSE_DECIDE", "COURSE_DECIDE",
                        {Clip{.id = "COURSE_DECIDE_outro_hold_snapped_to_centre",
                              .start = 400,
                              .command = SpriteAnimate{.asset = "expert",
                                                       .animation = "COURSE_DECIDE",
                                                       .priority = 31,
                                                       .playback = GcAnim::Playback::HoldLast,
                                                       .hidden_parts = {"SKM", "OPTION_1P",
                                                                        "OPTION_2P"}}}}),
            ModelTrack(
                "core", "core",
                {Clip{.id = "core_fly_in_from_the_eye_plane",
                      .end = 42,
                      .command =
                          ModelDraw{.asset = "red",
                                    .blend_mode = ModelBlend::Additive,
                                    .alpha = Widen(0.8F),
                                    .anim_speed = 0.75,
                                    .position = Widen(-0.19112459F, -0.00592613F, -0.7036935F),
                                    .rotation = Widen(0.0F, 2.19911F, 45.0F),
                                    .spin_per_frame = Widen(0.0F, 0.052359875F, 0.0F)}},
                 Clip{.id = "core_settled",
                      .start = 42,
                      .end = 400,
                      .command =
                          ModelDraw{.asset = "red",
                                    .blend_mode = ModelBlend::Additive,
                                    .alpha = Widen(0.8F),
                                    .anim_speed = 0.75,
                                    .position = Widen(-0.19112459F, -0.00592613F, -0.7036935F),
                                    .rotation = Widen(0.0F, 2.19911F, 45.0F),
                                    .spin_per_frame = Widen(0.0F, 0.052359875F, 0.0F)}},
                 Clip{.id = "core_outro_hold_snapped_to_centre",
                      .start = 400,
                      .end = 550,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .alpha = Widen(0.8F),
                                           .anim_speed = 0.75,
                                           .position = Widen(0.0F, 0.0F, -0.7F),
                                           .rotation = Widen(0.0F, 2.19911F, 45.0F),
                                           .spin_per_frame = Widen(0.0F, 0.052359875F, 0.0F)}},
                 Clip{.id = "core_outro_fade",
                      .start = 550,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .alpha = Widen(0.8F),
                                           .anim_speed = 0.75,
                                           .position = Widen(0.0F, 0.0F, -0.7F),
                                           .rotation = Widen(0.0F, 2.19911F, 45.0F),
                                           .spin_per_frame = Widen(0.0F, 0.052359875F, 0.0F)}}}),
            ModelTrack(
                "core_tween", "core",
                {Clip{.id = "core_tween_fly_in_from_the_eye_plane",
                      .end = 42,
                      .command = ModelTween{},
                      .keys = {Key{.at = 0,
                                   .ease = Ease::SineDeg,
                                   .rate_deg = Widen(2.368421F),
                                   .values = {KeyValue{.id = "position",
                                                       .value = Widen(0.2F, 0.0F, -1.0F)}}},
                               Key{.at = 42,
                                   .values = {KeyValue{.id = "position",
                                                       .value = Widen(-0.196F, -0.006F, -0.7F)}}}}},
                 Clip{.id = "core_tween_outro_fade",
                      .start = 550,
                      .command = ModelTween{},
                      .keys = {Key{.at = 0,
                                   .values = {KeyValue{.id = "alpha", .value = Widen(0.8F)}}},
                               Key{.at = 31, .values = {KeyValue{.id = "alpha", .value = 0.0}}}}}}),
            ModelTrack(
                "flame", "flame",
                {Clip{.id = "flame_fly_in_from_the_eye_plane",
                      .end = 42,
                      .command =
                          ModelDraw{.asset = "red",
                                    .anim_speed = 0.75,
                                    .position = Widen(-0.19112459F, -0.00592613F, -0.7036935F),
                                    .rotation = Widen(0.0F, -0.36652F, -0.18326F),
                                    .spin_per_frame = Widen(0.0F, -0.008726646F, -0.004363323F)}},
                 Clip{.id = "flame_settled",
                      .start = 42,
                      .end = 400,
                      .command =
                          ModelDraw{.asset = "red",
                                    .anim_speed = 0.75,
                                    .position = Widen(-0.19112459F, -0.00592613F, -0.7036935F),
                                    .rotation = Widen(0.0F, -0.36652F, -0.18326F),
                                    .spin_per_frame = Widen(0.0F, -0.008726646F, -0.004363323F)}},
                 Clip{.id = "flame_outro_hold_snapped_to_centre",
                      .start = 400,
                      .end = 550,
                      .command =
                          ModelDraw{.asset = "red",
                                    .anim_speed = 0.75,
                                    .position = Widen(0.0F, 0.0F, -0.7F),
                                    .rotation = Widen(0.0F, -0.36652F, -0.18326F),
                                    .spin_per_frame = Widen(0.0F, -0.008726646F, -0.004363323F)}},
                 Clip{.id = "flame_outro_fade",
                      .start = 550,
                      .command =
                          ModelDraw{.asset = "red",
                                    .anim_speed = 0.75,
                                    .position = Widen(0.0F, 0.0F, -0.7F),
                                    .rotation = Widen(0.0F, -0.36652F, -0.18326F),
                                    .spin_per_frame = Widen(0.0F, -0.008726646F, -0.004363323F)}}}),
            ModelTrack(
                "flame_tween", "flame",
                {Clip{.id = "flame_tween_fly_in_from_the_eye_plane",
                      .end = 42,
                      .command = ModelTween{},
                      .keys = {Key{.at = 0,
                                   .ease = Ease::SineDeg,
                                   .rate_deg = Widen(2.368421F),
                                   .values = {KeyValue{.id = "position",
                                                       .value = Widen(0.2F, 0.0F, -1.0F)}}},
                               Key{.at = 42,
                                   .values = {KeyValue{.id = "position",
                                                       .value = Widen(-0.196F, -0.006F, -0.7F)}}}}},
                 Clip{.id = "flame_tween_outro_fade",
                      .start = 550,
                      .command = ModelTween{},
                      .keys = {
                          Key{.at = 0, .values = {KeyValue{.id = "alpha", .value = 1.0}}},
                          Key{.at = 31, .values = {KeyValue{.id = "alpha", .value = 0.0}}}}}})}};
}

Document Iidx11ModeSelect() {
    return Document{
        .id = "iidx11-mode-select",
        .name = "Mode select",
        .build = "iidx11",
        .length = 1200,
        .camera = WideLensAt(Widen(-0.15F, 0.14F, -0.06F), Widen(1.12F, -1.31F, 1.28F)),
        .lights = StandardLights(),
        .assets = {Scene3dAsset("red", "data/graph/model/red")},
        .markers = {Marker{.frame = 0, .label = "Fly in, fast wind up"},
                    Marker{.frame = 15, .label = "Fly in, five times the accumulate"},
                    Marker{.frame = 28, .label = "Fly in, spin at its floor"},
                    Marker{.frame = 40, .label = "Interactive, unwinding"}},
        .tracks = {
            ModelTrack("core", "core",
                       {Clip{.id = "core_fly_in_fast_wind_up",
                             .end = 15,
                             .command = ModelDraw{.asset = "red",
                                                  .blend_mode = ModelBlend::Additive,
                                                  .anim_speed = 0.75,
                                                  .rotation = Widen(0.0F, 4.2F, 0.0F),
                                                  .spin_per_frame = Widen(0.0F, -0.008F, 0.0F)}},
                        Clip{.id = "core_fly_in_five_times_the_accumulate",
                             .start = 15,
                             .end = 28,
                             .command = ModelDraw{.asset = "red",
                                                  .blend_mode = ModelBlend::Additive,
                                                  .anim_speed = 0.75,
                                                  .rotation = Widen(0.0F, 4.2F, 0.0F),
                                                  .spin_per_frame = Widen(0.0F, -0.008F, 0.0F)}},
                        Clip{.id = "core_fly_in_spin_at_its_floor",
                             .start = 28,
                             .end = 40,
                             .command = ModelDraw{.asset = "red",
                                                  .blend_mode = ModelBlend::Additive,
                                                  .anim_speed = 0.75,
                                                  .spin_per_frame = Widen(0.0F, 0.04F, 0.0F)}},
                        Clip{.id = "core_interactive_unwinding",
                             .start = 40,
                             .command = ModelDraw{.asset = "red",
                                                  .blend_mode = ModelBlend::Additive,
                                                  .anim_speed = 0.75,
                                                  .rotation = Widen(0.0F, 4.2F, 0.0F),
                                                  .spin_per_frame = Widen(0.0F, -0.008F, 0.0F)}}}),
            ModelTrack(
                "core_tween", "core",
                {Clip{.id = "core_tween_fly_in_fast_wind_up",
                      .end = 15,
                      .command = ModelTween{},
                      .keys = {Key{.at = 0,
                                   .values = {KeyValue{.id = "spin_per_frame",
                                                       .value = Widen(0.0F, 0.12F, 0.0F)}}},
                               Key{.at = 15,
                                   .values = {KeyValue{.id = "spin_per_frame",
                                                       .value = Widen(0.0F, 0.064F, 0.0F)}}}}},
                 Clip{.id = "core_tween_fly_in_five_times_the_accumulate",
                      .start = 15,
                      .end = 28,
                      .command = ModelTween{},
                      .keys = {Key{.at = 0,
                                   .values = {KeyValue{.id = "spin_per_frame",
                                                       .value = Widen(0.0F, 0.3F, 0.0F)}}},
                               Key{.at = 13,
                                   .values = {KeyValue{.id = "spin_per_frame",
                                                       .value = Widen(0.0F, 0.06F, 0.0F)}}}}}}),
            ModelTrack("flame", "flame",
                       {Clip{.id = "flame_fly_in_fast_wind_up",
                             .end = 15,
                             .command = ModelDraw{.asset = "red",
                                                  .blend_mode = ModelBlend::Additive,
                                                  .anim_speed = 0.75,
                                                  .rotation = Widen(0.0F, 4.2F, 0.0F),
                                                  .spin_per_frame = Widen(0.0F, -0.008F, 0.0F)}},
                        Clip{.id = "flame_fly_in_five_times_the_accumulate",
                             .start = 15,
                             .end = 28,
                             .command = ModelDraw{.asset = "red",
                                                  .blend_mode = ModelBlend::Additive,
                                                  .anim_speed = 0.75,
                                                  .rotation = Widen(0.0F, 4.2F, 0.0F),
                                                  .spin_per_frame = Widen(0.0F, -0.008F, 0.0F)}},
                        Clip{.id = "flame_fly_in_spin_at_its_floor",
                             .start = 28,
                             .end = 40,
                             .command = ModelDraw{.asset = "red",
                                                  .blend_mode = ModelBlend::Additive,
                                                  .anim_speed = 0.75,
                                                  .spin_per_frame = Widen(0.0F, 0.04F, 0.0F)}},
                        Clip{.id = "flame_interactive_unwinding",
                             .start = 40,
                             .command = ModelDraw{.asset = "red",
                                                  .blend_mode = ModelBlend::Additive,
                                                  .anim_speed = 0.75,
                                                  .rotation = Widen(0.0F, 4.2F, 0.0F),
                                                  .spin_per_frame = Widen(0.0F, -0.008F, 0.0F)}}}),
            ModelTrack(
                "flame_tween", "flame",
                {Clip{.id = "flame_tween_fly_in_fast_wind_up",
                      .end = 15,
                      .command = ModelTween{},
                      .keys = {Key{.at = 0,
                                   .values = {KeyValue{.id = "spin_per_frame",
                                                       .value = Widen(0.0F, 0.12F, 0.0F)}}},
                               Key{.at = 15,
                                   .values = {KeyValue{.id = "spin_per_frame",
                                                       .value = Widen(0.0F, 0.064F, 0.0F)}}}}},
                 Clip{.id = "flame_tween_fly_in_five_times_the_accumulate",
                      .start = 15,
                      .end = 28,
                      .command = ModelTween{},
                      .keys = {Key{.at = 0,
                                   .values = {KeyValue{.id = "spin_per_frame",
                                                       .value = Widen(0.0F, 0.3F, 0.0F)}}},
                               Key{.at = 13,
                                   .values = {KeyValue{.id = "spin_per_frame",
                                                       .value = Widen(0.0F, 0.06F, 0.0F)}}}}}})}};
}

Document Iidx11MusicSelect() {
    return Document{
        .id = "iidx11-music-select",
        .name = "Music select",
        .build = "iidx11",
        .length = 3600,
        .camera = WideLens({0.0, 0.0, -1.0}),
        .lights = StandardLights(),
        .assets = {Scene3dAsset("red", "data/graph/model/red")},
        .options = {OptionSpec{
            .id = "attack",
            .label = "Screen variant",
            .transition = {.frames = 0, .step = 4},
            .choices = {ChoiceSpec{.label = "Normal",
                                   .values = {ChoiceValue{.id = "model[core].position",
                                                          .value = Vec3{0.0, 0.0, 0.0}}}},
                        ChoiceSpec{.label = "ATTACK",
                                   .values = {ChoiceValue{.id = "model[core].position",
                                                          .value = Vec3{0.0, 0.0, 0.0}}}}}}},
        .markers = {Marker{.frame = 0, .label = "Fly in, punching past the resting point"},
                    Marker{.frame = 35, .label = "Settled"}},
        .tracks = {
            ModelTrack(
                "core", "core",
                {Clip{.id = "core_fly_in_punching_past_the_resting_point",
                      .end = 35,
                      .when =
                          Gate{.option = "attack", .kind = GateKind::Not, .choices = {"ATTACK"}},
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .alpha = Widen(0.8F),
                                           .anim_speed = 0.75,
                                           .position = Widen(-0.1F, 0.0F, -0.27555564F),
                                           .rotation = Widen(0.0F, 4.712389F, 45.0F),
                                           .spin_per_frame = Widen(0.0F, 0.008726646F, 0.0F)}},
                 Clip{.id = "core_attack_fly_in_punching_past_the_resting_point",
                      .end = 35,
                      .when = Gate{.option = "attack", .choices = {"ATTACK"}},
                      .command =
                          ModelDraw{.asset = "red",
                                    .blend_mode = ModelBlend::Additive,
                                    .alpha = Widen(0.8F),
                                    .anim_speed = 0.75,
                                    .position = Widen(-0.05F, -0.01F, -0.8551111F),
                                    .rotation = Widen(0.0F, -std::numbers::pi_v<float>, 45.0F),
                                    .spin_per_frame = Widen(0.004363323F, 0.011635528F, 0.0F)}},
                 Clip{.id = "core_settled",
                      .start = 35,
                      .when =
                          Gate{.option = "attack", .kind = GateKind::Not, .choices = {"ATTACK"}},
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .alpha = Widen(0.8F),
                                           .anim_speed = 0.75,
                                           .position = Widen(-0.1F, 0.0F, -0.27555564F),
                                           .rotation = Widen(0.0F, 4.712389F, 45.0F),
                                           .spin_per_frame = Widen(0.0F, 0.008726646F, 0.0F)}},
                 Clip{.id = "core_attack_settled",
                      .start = 35,
                      .when = Gate{.option = "attack", .choices = {"ATTACK"}},
                      .command =
                          ModelDraw{.asset = "red",
                                    .blend_mode = ModelBlend::Additive,
                                    .alpha = Widen(0.8F),
                                    .anim_speed = 0.75,
                                    .position = Widen(-0.05F, -0.01F, -0.8551111F),
                                    .rotation = Widen(0.0F, -std::numbers::pi_v<float>, 45.0F),
                                    .spin_per_frame = Widen(0.004363323F, 0.011635528F, 0.0F)}}}),
            ModelTrack(
                "core_tween", "core",
                {Clip{.id = "core_tween_fly_in_punching_past_the_resting_point",
                      .end = 35,
                      .command = ModelTween{},
                      .keys = {Key{.at = 0,
                                   .ease = Ease::SineDeg,
                                   .rate_deg = 3.0,
                                   .values = {KeyValue{.id = "position",
                                                       .value = Widen(-0.1F, 0.0F, -1.0F)}}},
                               Key{.at = 35,
                                   .values = {KeyValue{.id = "position",
                                                       .value = Widen(-0.1F, 0.0F, -0.25F)}}}}}}),
            ModelTrack("core_tween_2", "core",
                       {Clip{.id = "core_tween_fly_in_punching_past_the_resting_point_2",
                             .end = 35,
                             .command = ModelTween{},
                             .keys = {Key{.at = 0,
                                          .ease = Ease::SineDeg,
                                          .rate_deg = Widen(2.6470587F),
                                          .values = {KeyValue{.id = "rotation",
                                                              .value = Vec3{0.0, 0.0, 45.0}}}},
                                      Key{.at = 34,
                                          .values = {KeyValue{
                                              .id = "rotation",
                                              .value = Widen(0.0F, 4.712389F, 45.0F)}}}}}}),
            ModelTrack(
                "shield", "shield",
                {Clip{.id = "shield_fly_in_punching_past_the_resting_point",
                      .end = 35,
                      .when =
                          Gate{.option = "attack", .kind = GateKind::Not, .choices = {"ATTACK"}},
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .alpha = Widen(0.525F),
                                           .anim_speed = 0.75,
                                           .position = Widen(-0.1F, 0.0F, -0.27555564F),
                                           .rotation = Widen(0.0F, 4.712389F, 45.0F),
                                           .spin_per_frame = Widen(0.0F, 0.008726646F, 0.0F)}},
                 Clip{.id = "shield_attack_fly_in_punching_past_the_resting_point",
                      .end = 35,
                      .when = Gate{.option = "attack", .choices = {"ATTACK"}},
                      .command =
                          ModelDraw{.asset = "red",
                                    .blend_mode = ModelBlend::Additive,
                                    .alpha = Widen(0.525F),
                                    .anim_speed = 0.75,
                                    .position = Widen(-0.05F, -0.01F, -0.8551111F),
                                    .rotation = Widen(0.0F, -9.424778F, 45.0F),
                                    .spin_per_frame = Widen(0.004363323F, 0.034906585F, 0.0F)}},
                 Clip{.id = "shield_settled",
                      .start = 35,
                      .when =
                          Gate{.option = "attack", .kind = GateKind::Not, .choices = {"ATTACK"}},
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .alpha = Widen(0.525F),
                                           .anim_speed = 0.75,
                                           .position = Widen(-0.1F, 0.0F, -0.27555564F),
                                           .rotation = Widen(0.0F, 4.712389F, 45.0F),
                                           .spin_per_frame = Widen(0.0F, 0.008726646F, 0.0F)}},
                 Clip{.id = "shield_attack_settled",
                      .start = 35,
                      .when = Gate{.option = "attack", .choices = {"ATTACK"}},
                      .command =
                          ModelDraw{.asset = "red",
                                    .blend_mode = ModelBlend::Additive,
                                    .alpha = Widen(0.525F),
                                    .anim_speed = 0.75,
                                    .position = Widen(-0.05F, -0.01F, -0.8551111F),
                                    .rotation = Widen(0.0F, -9.424778F, 45.0F),
                                    .spin_per_frame = Widen(0.004363323F, 0.034906585F, 0.0F)}}}),
            ModelTrack(
                "shield_tween", "shield",
                {Clip{.id = "shield_tween_fly_in_punching_past_the_resting_point",
                      .end = 35,
                      .command = ModelTween{},
                      .keys = {Key{.at = 0,
                                   .ease = Ease::SineDeg,
                                   .rate_deg = 3.0,
                                   .values = {KeyValue{.id = "position",
                                                       .value = Widen(-0.1F, 0.0F, -1.0F)}}},
                               Key{.at = 35,
                                   .values = {KeyValue{.id = "position",
                                                       .value = Widen(-0.1F, 0.0F, -0.25F)}}}}}}),
            ModelTrack("shield_tween_2", "shield",
                       {Clip{.id = "shield_tween_fly_in_punching_past_the_resting_point_2",
                             .end = 35,
                             .command = ModelTween{},
                             .keys = {Key{.at = 0,
                                          .ease = Ease::SineDeg,
                                          .rate_deg = Widen(2.6470587F),
                                          .values = {KeyValue{.id = "rotation",
                                                              .value = Vec3{0.0, 0.0, 45.0}}}},
                                      Key{.at = 34,
                                          .values = {KeyValue{
                                              .id = "rotation",
                                              .value = Widen(0.0F, 4.712389F, 45.0F)}}}}}}),
            ModelTrack(
                "flame", "flame",
                {Clip{.id = "flame_fly_in_punching_past_the_resting_point",
                      .end = 35,
                      .when =
                          Gate{.option = "attack", .kind = GateKind::Not, .choices = {"ATTACK"}},
                      .command = ModelDraw{.asset = "red",
                                           .anim_speed = 0.75,
                                           .position = Widen(-0.1F, 0.0F, -0.27555564F),
                                           .rotation = Widen(0.0F, 4.712389F, 45.0F),
                                           .spin_per_frame = Widen(0.0F, 0.008726646F, 0.0F)}},
                 Clip{.id = "flame_attack_fly_in_punching_past_the_resting_point",
                      .end = 35,
                      .when = Gate{.option = "attack", .choices = {"ATTACK"}},
                      .command =
                          ModelDraw{.asset = "red",
                                    .anim_speed = 0.75,
                                    .position = Widen(-0.05F, -0.01F, -0.8551111F),
                                    .rotation = Widen(0.0F, -9.424778F, 45.0F),
                                    .spin_per_frame = Widen(0.004363323F, 0.034906585F, 0.0F)}},
                 Clip{.id = "flame_settled",
                      .start = 35,
                      .when =
                          Gate{.option = "attack", .kind = GateKind::Not, .choices = {"ATTACK"}},
                      .command = ModelDraw{.asset = "red",
                                           .anim_speed = 0.75,
                                           .position = Widen(-0.1F, 0.0F, -0.27555564F),
                                           .rotation = Widen(0.0F, 4.712389F, 45.0F),
                                           .spin_per_frame = Widen(0.0F, 0.008726646F, 0.0F)}},
                 Clip{.id = "flame_attack_settled",
                      .start = 35,
                      .when = Gate{.option = "attack", .choices = {"ATTACK"}},
                      .command =
                          ModelDraw{.asset = "red",
                                    .anim_speed = 0.75,
                                    .position = Widen(-0.05F, -0.01F, -0.8551111F),
                                    .rotation = Widen(0.0F, -9.424778F, 45.0F),
                                    .spin_per_frame = Widen(0.004363323F, 0.034906585F, 0.0F)}}}),
            ModelTrack(
                "flame_tween", "flame",
                {Clip{.id = "flame_tween_fly_in_punching_past_the_resting_point",
                      .end = 35,
                      .command = ModelTween{},
                      .keys = {Key{.at = 0,
                                   .ease = Ease::SineDeg,
                                   .rate_deg = 3.0,
                                   .values = {KeyValue{.id = "position",
                                                       .value = Widen(-0.1F, 0.0F, -1.0F)}}},
                               Key{.at = 35,
                                   .values = {KeyValue{.id = "position",
                                                       .value = Widen(-0.1F, 0.0F, -0.25F)}}}}}}),
            ModelTrack("flame_tween_2", "flame",
                       {Clip{.id = "flame_tween_fly_in_punching_past_the_resting_point_2",
                             .end = 35,
                             .command = ModelTween{},
                             .keys = {Key{.at = 0,
                                          .ease = Ease::SineDeg,
                                          .rate_deg = Widen(2.6470587F),
                                          .values = {KeyValue{.id = "rotation",
                                                              .value = Vec3{0.0, 0.0, 45.0}}}},
                                      Key{.at = 34,
                                          .values = {KeyValue{
                                              .id = "rotation",
                                              .value = Widen(0.0F, 4.712389F, 45.0F)}}}}}}),
            ModelTrack(
                "r_side", "r_side",
                {Clip{.id = "r_side_fly_in_punching_past_the_resting_point",
                      .end = 35,
                      .when =
                          Gate{.option = "attack", .kind = GateKind::Not, .choices = {"ATTACK"}},
                      .command =
                          ModelDraw{.asset = "red",
                                    .blend_mode = ModelBlend::Additive,
                                    .alpha = Widen(0.65F),
                                    .anim_speed = 0.75,
                                    .position = Widen(-0.1F, 0.0F, -0.27555564F),
                                    .rotation = Widen(0.0F, 0.407243F, 0.305433F),
                                    .spin_per_frame = Widen(0.0F, 0.011635529F, 0.008726646F)}},
                 Clip{.id = "r_side_attack_fly_in_punching_past_the_resting_point",
                      .end = 35,
                      .when = Gate{.option = "attack", .choices = {"ATTACK"}},
                      .command =
                          ModelDraw{.asset = "red",
                                    .blend_mode = ModelBlend::Additive,
                                    .alpha = Widen(0.65F),
                                    .anim_speed = 0.75,
                                    .position = Widen(-0.05F, -0.01F, -0.8551111F),
                                    .rotation = Widen(0.0F, 0.407243F, 0.305433F),
                                    .spin_per_frame = Widen(0.0F, 0.011635529F, 0.008726646F)}},
                 Clip{.id = "r_side_settled",
                      .start = 35,
                      .when =
                          Gate{.option = "attack", .kind = GateKind::Not, .choices = {"ATTACK"}},
                      .command =
                          ModelDraw{.asset = "red",
                                    .blend_mode = ModelBlend::Additive,
                                    .alpha = Widen(0.65F),
                                    .anim_speed = 0.75,
                                    .position = Widen(-0.1F, 0.0F, -0.27555564F),
                                    .rotation = Widen(0.0F, 0.407243F, 0.305433F),
                                    .spin_per_frame = Widen(0.0F, 0.011635529F, 0.008726646F)}},
                 Clip{.id = "r_side_attack_settled",
                      .start = 35,
                      .when = Gate{.option = "attack", .choices = {"ATTACK"}},
                      .command =
                          ModelDraw{.asset = "red",
                                    .blend_mode = ModelBlend::Additive,
                                    .alpha = Widen(0.65F),
                                    .anim_speed = 0.75,
                                    .position = Widen(-0.05F, -0.01F, -0.8551111F),
                                    .rotation = Widen(0.0F, 0.407243F, 0.305433F),
                                    .spin_per_frame = Widen(0.0F, 0.011635529F, 0.008726646F)}}}),
            ModelTrack(
                "r_side_tween", "r_side",
                {Clip{.id = "r_side_tween_fly_in_punching_past_the_resting_point",
                      .end = 35,
                      .command = ModelTween{},
                      .keys = {Key{.at = 0,
                                   .ease = Ease::SineDeg,
                                   .rate_deg = 3.0,
                                   .values = {KeyValue{.id = "position",
                                                       .value = Widen(-0.1F, 0.0F, -1.0F)}}},
                               Key{.at = 35,
                                   .values = {KeyValue{.id = "position",
                                                       .value = Widen(-0.1F, 0.0F, -0.25F)}}}}}}),
            ModelTrack("r_side_tween_2", "r_side",
                       {Clip{.id = "r_side_tween_fly_in_punching_past_the_resting_point_2",
                             .end = 35,
                             .command = ModelTween{},
                             .keys = {Key{.at = 0,
                                          .ease = Ease::SineDeg,
                                          .rate_deg = Widen(2.6470587F),
                                          .values = {KeyValue{.id = "rotation",
                                                              .value = Vec3{0.0, 0.0, 0.0}}}},
                                      Key{.at = 34,
                                          .values = {KeyValue{
                                              .id = "rotation",
                                              .value = Widen(0.0F, 0.407243F, 0.305433F)}}}}}})}};
}

}

std::vector<Document> Iidx11SelectDefaults() {
    return {Iidx11DanSelect(), Iidx11ExpertSelect(), Iidx11ModeSelect(), Iidx11MusicSelect()};
}

}
