#include "preset/defaults/defaults_build.h"

#include "preset/doc/preset_commands.h"
#include "preset/doc/preset_document.h"
#include "preset/doc/preset_enum_names.h"

namespace Preset::Doc {

using namespace Build;

namespace {

DocumentPart Iidx11EndingPartA() {
    return DocumentPart{
        .markers = {Marker{.frame = 0, .label = "Black, models hidden"},
                    Marker{.frame = 71, .label = "Fade in, camera pulling back"},
                    Marker{.frame = 440, .label = "Burst, the spin-up whip"},
                    Marker{.frame = 814, .label = "Beat pulse"},
                    Marker{.frame = 1185, .label = "Core and flame counter-rotate"},
                    Marker{.frame = 1557, .label = "Second beat run"},
                    Marker{.frame = 1930, .label = "Beat 80, the flame unwinds"},
                    Marker{.frame = 2300, .label = "Camera pushes through"},
                    Marker{.frame = 2475, .label = "Snap back, triple speed"}},
        .tracks = {
            SpriteTrack(
                "END_BG1", "END_BG1",
                {Clip{.id = "END_BG1_black_models_hidden",
                      .end = 2300,
                      .command = SpriteDraw{.asset = "ending", .cell = "END_BG1", .priority = 31}},
                 Clip{.id = "END_BG1_camera_pushes_through",
                      .start = 2300,
                      .end = 2475,
                      .command = SpriteDraw{.asset = "ending", .cell = "END_BG1", .priority = 31},
                      .keys = {Key{.at = 0, .values = {KeyValue{.id = "scale", .value = 1.0}}},
                               Key{.at = 175, .values = {KeyValue{.id = "scale", .value = 9.75}}}}},
                 Clip{.id = "END_BG1_snap_back_triple_speed",
                      .start = 2475,
                      .end = 2486,
                      .command = SpriteDraw{.asset = "ending",
                                            .cell = "END_BG1",
                                            .scale = 2.0,
                                            .priority = 31}}}),
            ModelTrack(
                "core", "core",
                {Clip{.id = "core_fade_in_camera_pulling_back",
                      .start = 71,
                      .end = 440,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0},
                                           .spin_per_frame = Widen(0.0F, 0.017453292F, 0.0F)}},
                 Clip{.id = "core_burst_the_spin_up_whip",
                      .start = 440,
                      .end = 814,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0},
                                           .spin_per_frame = Widen(0.0F, 0.017453292F, 0.0F)}},
                 Clip{.id = "core_beat_pulse",
                      .start = 814,
                      .end = 1185,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0},
                                           .spin_per_frame = Widen(0.0F, 0.017453292F, 0.0F)}},
                 Clip{.id = "core_core_and_flame_counter_rotate",
                      .start = 1185,
                      .end = 1557,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0},
                                           .spin_per_frame = Widen(0.0F, 0.034906585F, 0.0F)}},
                 Clip{.id = "core_second_beat_run",
                      .start = 1557,
                      .end = 1930,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0},
                                           .spin_per_frame = Widen(0.0F, 0.017453292F, 0.0F)}},
                 Clip{.id = "core_beat_80_the_flame_unwinds",
                      .start = 1930,
                      .end = 2300,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0},
                                           .spin_per_frame = Widen(0.0F, 0.017453292F, 0.0F)}},
                 Clip{.id = "core_camera_pushes_through",
                      .start = 2300,
                      .end = 2475,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0},
                                           .spin_per_frame = Widen(0.0F, 0.017453292F, 0.0F)}},
                 Clip{.id = "core_snap_back_triple_speed",
                      .start = 2475,
                      .end = 2486,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0},
                                           .spin_per_frame = Widen(0.0F, -0.052359875F, 0.0F)}}}),
            ModelTrack(
                "core_tween", "core",
                {Clip{.id = "core_tween_fade_in_camera_pulling_back",
                      .start = 71,
                      .end = 440,
                      .command = ModelTween{},
                      .keys = {Key{.at = 0, .values = {KeyValue{.id = "alpha", .value = 0.0}}},
                               Key{.at = 60, .values = {KeyValue{.id = "alpha", .value = 1.0}}}}}}),
            ModelTrack("core_tween_2", "core", {}),
            ModelTrack("core_pulse", "core",
                       {Clip{.id = "core_pulse_beat_pulse",
                             .start = 814,
                             .end = 1185,
                             .command = ModelMotionCmd{.pulse = PulseSpec{.grid = Grid::A,
                                                                          .scale_odd = Widen(1.1F),
                                                                          .scale_even = Widen(1.1F),
                                                                          .frames = 8}}},
                        Clip{.id = "core_pulse_core_and_flame_counter_rotate",
                             .start = 1185,
                             .end = 1557,
                             .command = ModelMotionCmd{.pulse = PulseSpec{.grid = Grid::A,
                                                                          .scale_odd = Widen(1.1F),
                                                                          .scale_even = Widen(1.1F),
                                                                          .frames = 8}}},
                        Clip{.id = "core_pulse_second_beat_run",
                             .start = 1557,
                             .end = 1930,
                             .command = ModelMotionCmd{.pulse = PulseSpec{.grid = Grid::B,
                                                                          .scale_odd = Widen(1.1F),
                                                                          .scale_even = Widen(1.1F),
                                                                          .frames = 8}}},
                        Clip{.id = "core_pulse_beat_80_the_flame_unwinds",
                             .start = 1930,
                             .end = 2300,
                             .command = ModelMotionCmd{.pulse = PulseSpec{.grid = Grid::B,
                                                                          .scale_odd = Widen(1.1F),
                                                                          .scale_even = Widen(1.1F),
                                                                          .frames = 8}}}}),
            ModelTrack(
                "flame", "flame",
                {Clip{.id = "flame_fade_in_camera_pulling_back",
                      .start = 71,
                      .end = 440,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0},
                                           .spin_per_frame = Widen(0.0F, 0.017453292F, 0.0F)}},
                 Clip{.id = "flame_burst_the_spin_up_whip",
                      .start = 440,
                      .end = 814,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0},
                                           .spin_per_frame = Widen(0.0F, 0.017453292F, 0.0F)}},
                 Clip{.id = "flame_beat_pulse",
                      .start = 814,
                      .end = 1185,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0},
                                           .spin_per_frame = Widen(0.0F, 0.017453292F, 0.0F)}},
                 Clip{.id = "flame_core_and_flame_counter_rotate",
                      .start = 1185,
                      .end = 1557,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0},
                                           .spin_per_frame = Widen(0.0F, -0.017453292F, 0.0F)}},
                 Clip{.id = "flame_second_beat_run",
                      .start = 1557,
                      .end = 1930,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0},
                                           .spin_per_frame = Widen(0.0F, 0.017453292F, 0.0F)}},
                 Clip{.id = "flame_beat_80_the_flame_unwinds",
                      .start = 1930,
                      .end = 2300,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0},
                                           .spin_per_frame = Widen(0.0F, 0.017453292F, 0.0F)}},
                 Clip{.id = "flame_camera_pushes_through",
                      .start = 2300,
                      .end = 2475,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0},
                                           .spin_per_frame = Widen(0.0F, 0.017453292F, 0.0F)}},
                 Clip{.id = "flame_snap_back_triple_speed",
                      .start = 2475,
                      .end = 2486,
                      .command = ModelDraw{.asset = "red",
                                           .blend_mode = ModelBlend::Additive,
                                           .anim_speed = 0.75,
                                           .rotation = {0.0, 0.0, 45.0},
                                           .spin_per_frame = Widen(0.0F, -0.052359875F, 0.0F)}}}),
            ModelTrack(
                "flame_tween", "flame",
                {Clip{.id = "flame_tween_fade_in_camera_pulling_back",
                      .start = 71,
                      .end = 440,
                      .command = ModelTween{},
                      .keys = {Key{.at = 0, .values = {KeyValue{.id = "alpha", .value = 0.0}}},
                               Key{.at = 60, .values = {KeyValue{.id = "alpha", .value = 1.0}}}}},
                 Clip{
                     .id = "flame_tween_beat_80_the_flame_unwinds",
                     .start = 1930,
                     .end = 2300,
                     .command = ModelTween{},
                     .keys = {Key{.at = 0,
                                  .values = {KeyValue{.id = "rotation",
                                                      .value = Vec3{0.0, 0.0, 0.0}}}},
                              Key{.at = 369,
                                  .values = {KeyValue{.id = "rotation",
                                                      .value = Widen(0.0F, 0.0F, 6.4402647F)}}}}}}),
            ModelTrack("flame_pulse", "flame",
                       {Clip{.id = "flame_pulse_beat_pulse",
                             .start = 814,
                             .end = 1185,
                             .command = ModelMotionCmd{.pulse = PulseSpec{.grid = Grid::A,
                                                                          .scale_odd = Widen(1.1F),
                                                                          .scale_even = Widen(1.1F),
                                                                          .frames = 8}}},
                        Clip{.id = "flame_pulse_core_and_flame_counter_rotate",
                             .start = 1185,
                             .end = 1557,
                             .command = ModelMotionCmd{.pulse = PulseSpec{.grid = Grid::A,
                                                                          .scale_odd = Widen(1.1F),
                                                                          .scale_even = Widen(1.1F),
                                                                          .frames = 8}}},
                        Clip{.id = "flame_pulse_second_beat_run",
                             .start = 1557,
                             .end = 1930,
                             .command = ModelMotionCmd{.pulse = PulseSpec{.grid = Grid::B,
                                                                          .scale_odd = Widen(1.1F),
                                                                          .scale_even = Widen(1.1F),
                                                                          .frames = 8}}},
                        Clip{.id = "flame_pulse_beat_80_the_flame_unwinds",
                             .start = 1930,
                             .end = 2300,
                             .command = ModelMotionCmd{.pulse = PulseSpec{.grid = Grid::B,
                                                                          .scale_odd = Widen(1.1F),
                                                                          .scale_even = Widen(1.1F),
                                                                          .frames = 8}}}}),
            CameraTrack("camera", {Clip{.id = "camera_black_models_hidden",
                                        .end = 71,
                                        .command = CameraSet{.eye = Widen(0.0F, 0.0F, -0.3F)}},
                                   Clip{.id = "camera_snap_back_triple_speed",
                                        .start = 2475,
                                        .end = 2486,
                                        .command = CameraSet{.eye = Widen(0.0F, 0.0F, -0.3F)}}}),
            CameraTrack(
                "camera_tween",
                {Clip{.id = "camera_tween_fade_in_camera_pulling_back",
                      .start = 71,
                      .end = 440,
                      .command = CameraTween{},
                      .keys = {Key{.at = 0,
                                   .values = {KeyValue{.id = "eye", .value = Vec3{0.0, 0.0, 0.0}}}},
                               Key{.at = 126,
                                   .values = {KeyValue{.id = "eye",
                                                       .value = Widen(0.0F, 0.0F, 0.249F)}}}}},
                 Clip{.id = "camera_tween_camera_pushes_through",
                      .start = 2300,
                      .end = 2475,
                      .command = CameraTween{},
                      .keys = {Key{.at = 0,
                                   .values = {KeyValue{.id = "eye",
                                                       .value = Widen(0.0F, 0.0F, 0.249F)}}},
                               Key{.at = 175,
                                   .values = {KeyValue{.id = "eye",
                                                       .value = Widen(0.0F, 0.0F, -0.85F)}}}}}}),
            FxTrack("fx",
                    {Clip{.id = "fx_burst_the_spin_up_whip",
                          .start = 440,
                          .end = 814,
                          .command = EmitterCmd{.asset = "system",
                                                .cell = "PTC_ORAN",
                                                .count = 480,
                                                .priority = 24,
                                                .scale_percent = 200,
                                                .scatter = Scatter{.span = {1280.0, 960.0},
                                                                   .offset = {-320.0, -240.0}},
                                                .life = 45}}}),
            SceneTrack(
                "scene",
                {Clip{.id = "beat",
                      .command =
                          RhythmBeat{.rate = 155, .span = 3600, .offset_a = 70, .offset_b = 59}},
                 Clip{.id = "jitter_fade_in_camera_pulling_back",
                      .start = 431,
                      .end = 440,
                      .command = RhythmJitter{.span = 200, .scale = Widen(0.0001F)}},
                 Clip{.id = "jitter_burst_the_spin_up_whip",
                      .start = 724,
                      .end = 814,
                      .command = RhythmJitter{.span = 100, .scale = Widen(0.0001F)}}})}};
}

}

Document Iidx11Ending() {
    Document document = Document{.id = "iidx11-ending",
                                 .name = "Ending",
                                 .build = "iidx11",
                                 .length = 4385,
                                 .camera = WideLens(Widen(0.0F, 0.0F, 0.249F)),
                                 .lights = StandardLights(),
                                 .assets = {Scene3dAsset("red", "data/graph/model/red"),
                                            Package2dAsset("ending", "data/graph/sys/ending"),
                                            Package2dAsset("system", "data/graph/sys/system")}};
    AppendPart(document, Iidx11EndingPartA());
    AppendPart(document, Iidx11EndingPartB());
    return document;
}

}
