namespace PreviewProtocol;

table Boot {
  game_dir:string;
  build:string;
}

table LoadPackage {
  package:string;
  animation:string;
  ifs:[ubyte];
  reload:bool;
}

table SelectAnimation {
  name:string;
}

table Seek {
  frame:uint;
}

table Resize {
  width:uint;
  height:uint;
}

table Render {
}

union Request { Boot, LoadPackage, SelectAnimation, Seek, Resize, Render }

table RequestMessage {
  request:Request;
}

table Label {
  name:string;
  frame:uint;
}

table Done {
}

table Loaded {
  frame_count:uint;
  labels:[Label];
}

table Frame {
  shared_handle:ulong;
  width:uint;
  height:uint;
  frame:uint;
}

table Failure {
  message:string;
}

union Reply { Done, Loaded, Frame, Failure }

table ReplyMessage {
  reply:Reply;
}

root_type RequestMessage;
